SET DATABASE SQL SYNTAX MYS TRUE;

INSERT INTO Frame (ID, Name, Definition, SymbolicRep, Image, CreatedBy, CreatedDate, ModifiedDate) VALUES (1,'TestUp', 'The words in this frame take direct objects that denote entities in the world, and indicate awareness of those entities, without necessarily giving any information about the conten', NULL, NULL, 'test user', '2003-01-06 17:30:50', '2003-01-06 17:30:50' );
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Causation', 'The words in this frame take direct objects that denote entities in the world, and indicate awareness of those entities, without necessarily giving any information about the conten', 'alice');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES  ('Communication', 'The words in this frame take direct objects that denote entities in the world, and indicate awareness of those entities, without necessarily giving any information about the conten', 'alice');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES  ('Motion', 'The words in this frame take direct objects that denote entities in the world, and indicate awareness of those entities, without necessarily giving any information about the conten', 'alice');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES  ('Perception', 'The words in this frame take direct objects that denote entities in the world, and indicate awareness of those entities, without necessarily giving any information about the conten', 'alice');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES  ('Reciprocality', 'The words in this frame take direct objects that denote entities in the world, and indicate awareness of those entities, without necessarily giving any information about the conten', 'alice');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Certainty', '<def-root>A <fen>Cause</fen>, animate or inanimate, causes an <fen>Effect</fen>. Those frames that inherit the Causation frame convey the idea that some event is responsible for the occurrence', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Activity', '<def-root>Words in this frame have to do with a Cognizer believing that some Phenomenon will take place in the future. <ex><fex name="Cog">Michael</fex> <t>expected</t> <fex name="Phen">Abby</fex> <fex name="Phen">to demand examples</fex>.</ex>', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Activity_finish', '<def-root>This frame contains adjectives and nouns that describe the truth or sincerity of communication. These words, analogously to behaver-evaluating words, can apply either to <fen>Speaker</fen>s or to the <fen>Message</fen>s they produce.', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Activity_start', '<def-root>Words in this frame have to do with a <fen>Cognizer</fen> creating a new intellectual entity, the <fen>Invention</fen>. These words are similar to words of physical creation such as <ment>build</ment> and <ment>make</ment>, ', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Activity_stop', '<def-root>These words describe the size of message that a <fen>Speaker</fen> is judged by a (usually unexpressed) <fen>Judge</fen> to give, either in a specific occasion or <fen>Topic</fen> or in general. As in other communication frames', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Activity_resume', '<def-root>The words in this frame describe the "fictive" motion of a stationary Road. Some of the targets cast the scene primarily in terms of the Path_shape: ', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Activity_pause', '<def-root>These are words describing situations in which a <fen>Perpetrator</fen> takes something (<fen>Goods</fen>) from a <fen>Victim</fen> that does not belong to him . The robbery can be done in a particular <fen>Manner</fen> ', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Activity_prepare', '<def-root>An <fen>Emitter</fen> emits a <fen>Beam</fen> of light from a <fen>Source</fen>, along a <fen>Path</fen>, and/or towards a <fen>Goal</fen>.  Essentially, this frame denotes the (semi-)fictive motion of the the <fen>Beam</fen>. ', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Reporting', '<def-root>This frame is concerned with transparent nouns denoting a <fen>Piece</fen> of a <fen>Substance</fen>. Also present is <fen>Piece_prop</fen> which is a property of the <fen>Piece</fen>, e.g. relating to its size.<ex>Kim ate a <fex', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Statement', '<def-root>An <fen>Agent</fen> begins an <fen>Activity</fen> at a certain <fen>Place</fen> and <fen>Time</fen>.</def-root>', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Evidence', '<def-root>A <fen>Figure</fen> is located relative to a <fen>Ground</fen> location.  The location of the <fen>Figure</fen> may be further specified by its <fen>Distance</fen> from a reference location (generally, the deictic center) and the', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Judgement', '<def-root>A <fen>Protagonist</fen> is sensitive to a <fen>Trigger</fen>, which has the potential to cause some kind of reaction in the <fen>Protagonist</fen>. </def-root>', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Arriving', '<def-root>This frame contains words that necessarily indicate the motion of two distinct objects. The <fen>Theme</fen> is typically animate and is expressed the same way a Self-mover is expressed in the Self-motion frame', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Self_motion', '<def-root>In this frame a <fen>Speaker</fen> asks an <fen>Addressee</fen> for something, or to carry out some action.', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Request', 'This frame involves a <fen>Creator</fen> making an imitation or fake (the <fen>Copy</fen>) of some <fen>Original</fen> entity. ', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Statement', '<def-root>This frame contains verbs and nouns that communicate the act of a <fen>Speaker</fen> to address a <fen>Message</fen> to some <fen>Addressee</fen> using language. ', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Discussion', '<def-root>Two (or more) people (the <fen>Interlocutors</fen>, also encodable as <fen>Interlocutor_1</fen> and <fen>Interlocutor_2</fen>) talk to one another. No person is construed as only a speaker or only an addressee.', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Gesture', '<def-root>The words in this frame have to do with non-verbal communication. Topic is not normally expressed with these words. This seems to be related to the absence of a verbal code in cases of gestural communication. ', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Recovery', '<def-root>These words describe the recovery or healing of a <fen>Patient</fen> from an <fen>Affliction</fen> without reference to the influence of any Treatment or Healer (see the Cure frame). </def-root>', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Filling', '<def-root>These are words relating to filling containers and covering areas with some thing, things or substance, the <fen>Theme</fen>. The area or container can appear as the direct object with all these verbs, and ', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Placing', '<def-root>Generally without overall motion,  an <fen>Agent</fen> places a <fen>Theme</fen> at a location, the <fen>Goal</fen>, which is profiled.  In this frame, the <fen>Theme</fen> is under th', 'test user');
INSERT INTO Frame (Name, Definition, CreatedBy) VALUES ('Telling', 'test definition', 'test user');

INSERT INTO PartOfSpch (ID, Name, Definition) VALUES (84, 'A', 'Adjective');

INSERT INTO Lemma (ID, CreatedBy, CreatedDate, ModifiedDate, PartOfSpch_Ref) VALUES (1, 'test user', '2003-01-06 17:30:50', '2003-01-06 17:30:50', 84);

INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref, Lemma_Ref) VALUES (1,'test user', 'testLex',0, 1, 1);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (2,'shizuka', '盗む.v',0, 1);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (3,'shizuka', '回る.v',0, 1);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (4,'shizuka', 'たどりつく.v',0, 2);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (5,'shizuka', 'いい.a',0, 2);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (6,'shizuka', 'いい.a',0, 3);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (7,'shizuka', 'いい.a',0, 4);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (8,'test user', 'test.v',0, 4);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (9,'test user', 'tell apart.v',0, 5);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (10,'test user', 'tell.v',0, 6);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (11,'test user', 'tell.v',0, 7);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (12,'test user', 'telling off.n',0, 8);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (13,'test user', 'あせる.v',0, 8);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (14,'test user', '苛立つ.v',0, 10);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (15,'test user', '怨む.v',0, 12);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (16,'test user', '恐れる.v',0, 13);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (17,'test user', 'おののく.v',0, 16);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (18,'test user', '怯える.v',0, 17);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (19,'test user', '目.n',0, 5);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (20,'test user', 'のぞく.v',0, 4);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (22,'test user', 'おぼえる.v',0, 23);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (23,'test user', '止まる.v',0, 13);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (24,'test user', '伺う.v',0, 16);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (25,'test user', '泣く.v',0, 17);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (26,'test user', '見つける.v',0, 5);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (27,'test user', '通る.v',0, 16);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (28,'test user', '買う.v',0, 18);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (29,'test user', '買う.v',0, 19);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (30,'test user', 'たどりつく.v',0, 21);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (31,'test user', '聞く.v',0, 11);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (32,'test user', '行く.v',0, 22);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (33,'test user', '多い.a',0, 15);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (34,'test user', '動く.v',0, 24);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (35,'test user', '上がる.v',0, 24);
INSERT INTO LexUnit (ID, CreatedBy, Name, ImportNum, Frame_Ref) VALUES (36,'test user', '回る.v',0, 25);


INSERT INTO StatusType (ID,Name, Description, Rank) VALUES (1, 'New', 'LU defined and sentences ready for annotation', 20);
INSERT INTO StatusType (ID,Name, Description, Rank) VALUES (2, 'Created', 'LU defined in frame, but sentences not yet extracted from corpus', 20);
INSERT INTO StatusType (ID,Name, Description, Rank) VALUES (3, 'Finished_Checked', 'Annotation and final checking completed during FrameNet II', 20);

INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10021, NULL, 'shizuka', '2005-05-11 18:56:21', 1, 1);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10022, NULL, 'shizuka', '2005-05-11 18:56:21', 2, 2);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10023, NULL, 'shizuka', '2005-05-11 18:56:21', 3, 2);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10024, NULL, 'shizuka', '2005-05-11 18:56:21', 4, 2);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10028, NULL, 'shizuka', '2005-05-11 18:56:21', 4, 3);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10025, NULL, 'shizuka', '2005-05-11 18:56:21', 5, 3);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10026, NULL, 'shizuka', '2005-05-11 18:56:21', 6, 2);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10027, NULL, 'shizuka', '2005-05-11 18:56:21', 7, 2);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10033, NULL, 'shizuka', '2005-05-11 18:56:21', 8, 2);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10029, NULL, 'shizuka', '2005-05-11 18:56:21', 9, 1);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10030, NULL, 'shizuka', '2005-05-11 18:56:21', 10, 1);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10031, NULL, 'shizuka', '2005-05-11 18:56:21', 11, 2);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10032, NULL, 'shizuka', '2005-05-11 18:56:21', 12, 3);
INSERT INTO Status (ID, Text, CreatedBy, ModifiedDate, LexUnit_Ref, StatusType_Ref) VALUES (10034, NULL, 'shizuka', '2005-05-11 18:56:21', 12, 2);

INSERT INTO Corpus (ID, Name, Description) VALUES (1, 'BCCWJ_CORE_OC_YAHOO_知恵袋_v1_1', 'BCCWJ v1.1 CORE Data Yahoo!知恵袋 Q&A | NumTrans 非適用 | Disc3_CORE_OT_core_M-XML');
INSERT INTO Corpus (ID, Name, Description) VALUES (2, 'BCCWJ_CORE_OW_白書_v1_1', 'BCCWJ v1.1 CORE Data Yahoo!知恵袋 Q&A | NumTrans 非適用 | Disc3_CORE_OT_core_M-XML');
INSERT INTO Corpus (ID, Name, Description) VALUES (3, 'BCCWJ_CORE_PB_書籍_v1_1', 'BCCWJ v1.1 CORE Data Yahoo!知恵袋 Q&A | NumTrans 非適用 | Disc3_CORE_OT_core_M-XML');

INSERT INTO Document (ID, Author, Name, Description, CreatedDate, CreatedBy, ModifiedDate, Corpus_Ref) VALUES (10061, NULL, 'sb100042.KNP', 'sb100042.KNP', '2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52', 1);
INSERT INTO Document (ID, Author, Name, Description, CreatedDate, CreatedBy, ModifiedDate, Corpus_Ref) VALUES (10062, NULL, '950108.KNP', 'sb100042.KNP', '2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52', 1);
INSERT INTO Document (ID, Author, Name, Description, CreatedDate, CreatedBy, ModifiedDate, Corpus_Ref) VALUES (10063, NULL, 'mai020214.KNP', 'sb100042.KNP', '2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52', 2);
INSERT INTO Document (ID, Author, Name, Description, CreatedDate, CreatedBy, ModifiedDate, Corpus_Ref) VALUES (10064, NULL, '9507ED.KNP', 'sb100042.KNP', '2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52', 2);
INSERT INTO Document (ID, Author, Name, Description, CreatedDate, CreatedBy, ModifiedDate, Corpus_Ref) VALUES (10065, NULL, '9502ED.KNP', 'sb100042.KNP', '2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52', 3);
INSERT INTO Document (ID, Author, Name, Description, CreatedDate, CreatedBy, ModifiedDate, Corpus_Ref) VALUES (10066, NULL, 'PB39_00059.KNP', 'sb100042.KNP', '2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52', 3);
INSERT INTO Document (ID, Author, Name, Description, CreatedDate, CreatedBy, ModifiedDate, Corpus_Ref) VALUES (10067, NULL, 'PB50_00012.KNP', 'sb100042.KNP', '2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52', 3);
INSERT INTO Document (ID, Author, Name, Description, CreatedDate, CreatedBy, ModifiedDate, Corpus_Ref) VALUES (10068, NULL, 'PB39_00193.KNP', 'sb100042.KNP', '2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52', 3);

INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (1, 'Cause', 'Cause', '<def-root>An animate or inanimate entity, a force, or event that produces an effect. Volitionality is not a necessary characteristic of <fen>Cause</fen>s.', 1, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (2, 'Affected', 'Affected', '<def-root>Agents in a joint or reciprocal action (e.g. exchange)</def-root>', 2, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (3, 'Effect', 'Effect', '<def-root>A positive or negative evaluation of the Phenomenon.<ex><fex name="Effect">低温でセルがかからないのは</fex>主に内部抵抗の上昇<t>より</t>ます。</ex></def-root>', 1, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (4, 'Communicator', 'Com', '<def-root>The person who uses language in the written or spoken modality to convey a Message to another person. <ex><fex name="Communicator">He</fex> finds it hard to <t>communicate</t> with people', 3, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (5, 'Addressee', 'Add', '<def-root>The <fen>Addressee</fen> receives a <fen>Message</fen> from the <fen>Communicator</fen>. ', 1, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (6, 'Message', 'Msg', '<def-root><fen>Message</fen> A proposition or set of propositions that the <fen>Communicator</fen> wants the', 5, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (7, 'Topic', 'Top', '<def-root>Topic is the entity that the proposition or propositions conveyed relate to, that they are about.', 1, 'Peripheral', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (8, 'Medium', 'Medium', '<def-root>The physical or abstract setting in which the Message is conveyed. ', 1, 'Peripheral', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (9, 'Theme', 'Thm', '<def-root>The <fen>Theme</fen> is the entity that changes location. Note that it is not a self-mover.',5 , 'Extra-Thematic', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (10, 'Source', 'Src', '<def-root>The <fen>Source</fen> is the location the <fen>Theme</fen> occupies initially before its change of location.', 2, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (11, 'Path', 'Path', '<def-root>The <fen>Path</fen> refers to (a part of) the ground over which the <fen>Theme</fen> travels  or to a landmark by which the <fen>Theme</fen> travels.', 2, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (12, 'Goal', 'Goal', '<def-root>The <fen>Goal</fen> is the location the <fen>Theme</fen> ends up in.', 1, 'Peripheral', 'N','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (13, 'Area', 'Area', '<def-root><fen>Area</fen> identifies the setting in which the <fen>Theme</fen>''s movement takes place without a specified <fen>Path</fen>.', 2, 'Peripheral', 'N','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (14, 'Perceiver', 'Perc', '<def-root>The FE <fen>Perceiver</fen> refers to someone whose cognitive state or experience (e.g. knowledge, beliefs, ideas judgments or classifications) is being described.</def-root>', 4, 'Peripheral', 'N','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (15, 'Phenomenon', 'Phen', '<def-root>An animate or inanimate entity, a force, or event that produces an effect. Volitionality is not a necessary characteristic of <fen>Cause</fen>s.', 4, 'Peripheral', 'N','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (16, 'Agent', 'Agt', '<def-root>Agent is the entity that acts on another entity.  </def-root>.', 5, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (17, 'Topic', 'Top', '<def-root>Topic is the entity that the proposition or propositions conveyed relate to, that they are about.', 8, 'Peripheral', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (18, 'Medium', 'Medium', '<def-root>The physical or abstract setting in which the Message is conveyed. ', 7, 'Peripheral', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (19, 'Theme', 'Thm', '<def-root>The <fen>Theme</fen> is the entity that changes location. Note that it is not a self-mover.',6 , 'Extra-Thematic', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (20, 'Source', 'Src', '<def-root>The <fen>Source</fen> is the location the <fen>Theme</fen> occupies initially before its change of location.', 7, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (21, 'Path', 'Path', '<def-root>The <fen>Path</fen> refers to (a part of) the ground over which the <fen>Theme</fen> travels  or to a landmark by which the <fen>Theme</fen> travels.', 7, 'Core', 'Y','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);
INSERT INTO FrameElement (ID, Name, Abbrev, Definition, Frame_Ref, Type, Core, CreatedDate, CreatedBy, ModifiedDate, SemRoleRank) VALUES (22, 'Goal', 'Goal', '<def-root>The <fen>Goal</fen> is the location the <fen>Theme</fen> ends up in.', 7, 'Peripheral', 'N','2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52',0);

INSERT INTO RelationType (ID, Name, SuperFrameName, SubFrameName, Profiles, Complete) VALUES (1, 'Inheritance','Parent','Child',0,1 );
INSERT INTO RelationType (ID, Name, SuperFrameName, SubFrameName, Profiles, Complete) VALUES (2, 'Subframe','Complex','Component',1,0 );
INSERT INTO RelationType (ID, Name, SuperFrameName, SubFrameName, Profiles, Complete) VALUES (3, 'Using','Parent','Child',0,1 );
INSERT INTO RelationType (ID, Name, SuperFrameName, SubFrameName, Profiles, Complete) VALUES (4, 'See_also','MainEntry','ReferringEntry',0,1 );
INSERT INTO RelationType (ID, Name, SuperFrameName, SubFrameName, Profiles, Complete) VALUES (5, 'Precedes','Earlier','Later',0,1 );
INSERT INTO RelationType (ID, Name, SuperFrameName, SubFrameName, Profiles, Complete) VALUES (6, 'Causative_of','Causative','Inchoative/state',0,1 );
INSERT INTO RelationType (ID, Name, SuperFrameName, SubFrameName, Profiles, Complete) VALUES (7, 'Perspective_on','Neutral','Perspectivized',0,1 );

INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (1,1,2,7,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (2,8,4,7,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (3,9,6,6,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (4,15,25,6,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (5,7,4,3,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (6,13,17,3,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (7,5,22,3,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (8,4,20,3,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (9,15,26,2,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (10,19,22,2,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (11,14,20,1,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (12,10,9,6,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (13,4,2,7,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (14,1,13,1,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (15,15,2,2,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');
INSERT INTO FrameRelation (ID, SuperFrame_Ref, SubFrame_Ref, RelationType_Ref, Profiled, CreatedDate, CreatedBy, ModifiedDate) VALUES (16,3,5,7,2,'2005-11-03 03:21:56', 'shizuka', '2015-07-16 08:18:52');