SET DATABASE SQL SYNTAX MYS TRUE;

DROP TABLE Frame IF EXISTS;
CREATE TABLE Frame (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  Name varchar(80) NOT NULL UNIQUE,
  Definition varchar(255) DEFAULT NULL,
  SymbolicRep varchar(80) DEFAULT NULL,
  Image mediumblob,
  CreatedBy varchar(40) NOT NULL,
  CreatedDate timestamp DEFAULT NULL,
  ModifiedDate timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS PartOfSpch;
CREATE TABLE PartOfSpch (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  Name varchar(80) DEFAULT NULL,
  Definition varchar(255) DEFAULT NULL
);

DROP TABLE IF EXISTS Lemma;
CREATE TABLE Lemma (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  CreatedBy varchar(40) NOT NULL,
  CreatedDate timestamp DEFAULT NULL,
  ModifiedDate timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PartOfSpch_Ref int DEFAULT NULL
);

DROP TABLE LexUnit IF EXISTS;
CREATE TABLE LexUnit (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  Name varchar(80) NOT NULL,
  SenseDesc varchar(255) DEFAULT NULL,
  Frame_Ref int NOT NULL,
  Lemma_Ref int NOT NULL,
  CreatedBy varchar(40) NOT NULL,
  CreatedDate timestamp DEFAULT NULL,
  ModifiedDate timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  IncorporatedFE int DEFAULT 0 ,
  ImportNum int DEFAULT 0, 
);

DROP TABLE IF EXISTS StatusType;
CREATE TABLE StatusType (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  Name varchar(40) DEFAULT NULL,
  Description varchar(255) DEFAULT NULL,
  Icon blob,
  Rank int DEFAULT NULL
);

DROP TABLE IF EXISTS Status;
CREATE TABLE Status (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  Text varchar(255) DEFAULT NULL,
  CreatedDate timestamp DEFAULT NULL,
  CreatedBy varchar(40) NOT NULL,
  ModifiedDate timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  StatusType_Ref int DEFAULT NULL,
  LexUnitRef int DEFAULT NULL
);

DROP TABLE IF EXISTS Document;
CREATE TABLE Document (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  Author varchar(80) DEFAULT NULL,
  Name varchar(80) DEFAULT NULL,
  Description varchar(255) DEFAULT NULL,
  Corpus_Ref int DEFAULT 0,
  CreatedDate timestamp DEFAULT NULL,
  CreatedBy varchar(40) NOT NULL,
  ModifiedDate timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
);