SET foreign_key_checks = 0;
INSERT INTO jfnwat.`Corpus` (`ID`, `Name`, `Description`, `CreatedDate`, `CreatedBy`, `ModifiedDate`) SELECT * FROM jfn02.`Corpus`;
INSERT INTO jfnwat.`Genre`(`ID`,`Name`) SELECT * FROM jfn02.`Genre`;
INSERT INTO jfnwat.`Document` (`ID`, `Author`, `Name`, `Description`, `Corpus_Ref`, `CreatedDate`, `CreatedBy`, `ModifiedDate`) SELECT * FROM jfn02.`Document`;
INSERT INTO jfnwat.`Document_Genre`(`Genre_Ref`,`Document_Ref`) SELECT * FROM jfn02.`Document_Genre`;
INSERT INTO jfnwat.`Paragraph` (`ID`, `DocumentOrder`, `Document_Ref`, `CreatedDate`, `CreatedBy`, `ModifiedDate`) SELECT * FROM jfn02.`Paragraph`;
INSERT INTO jfnwat.`Sentence` (`ID`, `Text`, `ParagraphOrder`, `AbsolutePos`, `CreatedDate`, `CreatedBy`, `Paragraph_Ref`, `ModifiedDate`, `ExternalID`) SELECT * FROM jfn02.`Sentence`;
INSERT INTO jfnwat.`Frame` (`ID`, `Name`, `Definition`, `CreatedDate`, `CreatedBy`, `Image`, `SymbolicRep`, `ModifiedDate`) SELECT * FROM jfn02.Frame;
INSERT INTO jfnwat.`PartOfSpch` (`ID`, `Name`, `Definition`) SELECT * FROM jfn02.`PartOfSpch`;
INSERT INTO jfnwat.`Lemma` (`ID`, `CreatedDate`, `CreatedBy`, `PartOfSpch_Ref`, `ModifiedDate`) SELECT * FROM jfn02.`Lemma`;
INSERT INTO jfnwat.`Lexeme` (`ID`, `CreatedDate`, `CreatedBy`, `Name`, `ModifiedDate`, `PartOfSpch_Ref`) SELECT * FROM jfn02.`Lexeme`;
INSERT INTO jfnwat.`WordForm` (`ID`, `Form`, `Lexeme_Ref`, `CreatedDate`, `CreatedBy`, `ModifiedDate`) SELECT * FROM jfn02.`WordForm`;
INSERT INTO jfnwat.`LexemeEntry` (`BreakBefore`, `Lexeme_Ref`, `Lemma_Ref`, `Headword`, `ID`, `ModifiedDate`, `CreatedDate`, `CreatedBy`, `LexemeOrder`) SELECT * FROM jfn02.`LexemeEntry`;
INSERT INTO jfnwat.`LexUnit` (`ID`, `SenseDesc`, `CreatedDate`, `CreatedBy`, `Lemma_Ref`, `Frame_Ref`, `Name`, `ModifiedDate`, `ImportNum`, `IncorporatedFE`) SELECT * FROM jfn02.`LexUnit`;
INSERT INTO jfnwat.`RevisedLus` (`ID`, `LexUnitID`, `CreatedDate`, `CreatedBy`, `ModifiedDate`, `DeletedLuID`) SELECT * FROM jfn02.`RevisedLus`;
INSERT INTO jfnwat.`Construction`(`ID`,`Name`,`Definition`,`CreatedDate`,`CreatedBy`,`Image`,`SymbolicRep`,`ModifiedDate`) SELECT * FROM jfn02.`Construction`;
INSERT INTO jfnwat.`ConstructElement`(`ID`,`Name`,`Abbrev`,`Definition`,`CreatedDate`,`CreatedBy`,`Construction_Ref`,`ModifiedDate`) SELECT * FROM jfn02.`ConstructionElement`;
INSERT INTO jfnwat.`SubCorpus` (`ID`, `Name`, `Rank`, `LexUnit_Ref`, `ModifiedDate`, `CreatedDate`, `CreatedBy`, `Construction_Ref`) SELECT * FROM jfn02.`SubCorpus`;
INSERT INTO jfnwat.`StatusType`(`ID`, `Name`, `Description`, `Icon`, `Rank`) SELECT * FROM jfn02.`StatusType`;
INSERT INTO jfnwat.`Status` (`ID`, `Text`, `CreatedDate`, `CreatedBy`, `ModifiedDate`, `StatusType_Ref`, `LexUnit_Ref`) SELECT * FROM jfn02.`Status` WHERE (`LexUnit_Ref`IN (SELECT ID FROM jfn02.`LexUnit`));
INSERT INTO jfnwat.`SemanticType` (`ID`, `Name`, `Description`, `CreatedDate`, `Createdby`, `ModifiedDate`, `Abbrev`) SELECT * FROM jfn02.`SemanticType`;
INSERT INTO jfnwat.`STInherit` (`ParentST_Ref`, `ChildST_Ref`) SELECT * FROM jfn02.`STInherit`;
INSERT INTO jfnwat.`SemanticType_LexUnit` (`SemanticType_Ref`, `LexUnit_Ref`) SELECT * FROM jfn02.`SemanticType_LexUnit`;
INSERT INTO jfnwat.`SemanticType_Frame` (`Frame_Ref`, `SemanticType_Ref`) SELECT * FROM jfn02.`SemanticType_Frame`;
INSERT INTO jfnwat.`FrameElement` (`ID`, `Name`, `Abbrev`, `Definition`, `SemRoleRank`, `Type`, `Core`, `CreatedDate`, `CreatedBy`, `Frame_Ref`, `ModifiedDate`) SELECT * FROM jfn02.`FrameElement`;
INSERT INTO jfnwat.`SemanticType_FrameElement` (`FrameElement_Ref`, `SemanticType_Ref`) SELECT * FROM jfn02.`SemanticType_FrameElement`;
INSERT INTO jfnwat.`RelationType` (`ID`, `Name`, `Description`, `SuperFrameName`, `SubFrameName`, `Profiles`, `Complete`) SELECT * FROM jfn02.`RelationType`;
INSERT INTO jfnwat.`FERelationType`(`ID`,`Name`,`Description`,`RelationType_Ref`) SELECT * FROM jfn02.`FERelationType`;
INSERT INTO jfnwat.`FrameRelation` (`ID`, `Profiled`, `SuperFrame_Ref`, `SubFrame_Ref`, `RelationType_Ref`, `CreatedDate`, `CreatedBy`, `ModifiedDate`, `Name`) SELECT * FROM jfn02.`FrameRelation`;
INSERT INTO jfnwat.`FERelation` (`ID`, `SuperFrameElement_Ref`, `SubFrameElement_Ref`, `FrameRelation_Ref`, `CreatedDate`, `CreatedBy`, `ModifiedDate`, `FERelationType_Ref`) SELECT * FROM jfn02.`FERelation` WHERE (`FrameRelation_Ref` IN (SELECT ID FROM jfnwat.`FrameRelation`));
INSERT INTO jfnwat.`Sequence` (`Name`, `Value`) SELECT * FROM jfn02.`Sequence`;
INSERT INTO jfnwat.`Layer` (`ID`, `CreatedDate`, `CreatedBy`, `AnnotationSet_Ref`, `LayerType_Ref`, `ModifiedDate`, `Rank`) SELECT * FROM jfn02.`Layer`;
INSERT INTO jfnwat.`NoteType` (`ID`, `Name`) SELECT * FROM jfn02.`NoteType`;
INSERT INTO jfnwat.`Note` (`ID`, `Text`, `CreatedDate`, `CreatedBy`, `NoteType_Ref`, `ModifiedDate`) SELECT * FROM jfn02.`Note`;
INSERT INTO jfnwat.`MiscLabel` (`ID`, `Name`, `Definition`) SELECT * FROM jfn02.`MiscLabel`;
INSERT INTO jfnwat.`InstantiationType` (`ID`, `Name`, `Description`, `Display`) SELECT * FROM jfn02.`InstantiationType`;
INSERT INTO jfnwat.`Color` (`ID`, `Name`, `rgb`) SELECT * FROM jfn02.Color;
INSERT INTO jfnwat.`LayerType` (`ID`, `Name`, `AllowsApositional`, `LGroup`, `Definition`, `IsAnnotation`) SELECT * FROM jfn02.`LayerType`;
INSERT INTO jfnwat.`AnnotationStatus` (`ID`, `Name`, `Description`) SELECT * FROM jfn02.`AnnotationStatus`;
INSERT INTO jfnwat.`AnnotationSet` (`ID`, `LexUnit_Ref`, `SubCorpus_Ref`, `Sentence_Ref`, `CreatedDate`, `CreatedBy`, `ModifiedDate`, `CurrentAnnoStatus_Ref`, `Construction_Ref`) SELECT * FROM jfn02.`AnnotationSet`;
INSERT INTO jfnwat.`ReFraming`(`ID`,`LexUnit_Ref`,`FrameRelation_Ref`,`AnnotationSet_Ref`,`CreatedBy`,`CreatedDate`,`ModifiedDate`) SELECT * FROM jfn02.`ReFraming`;
INSERT INTO jfnwat.`LabelType` (`ID`, `FgColorS_Ref`, `BgColorS_Ref`, `FgColorP_Ref`, `BgColorP_Ref`, `Keystroke`, `LayerType_Ref`, `MiscLabel_Ref`) SELECT `ID`, `FgColorS_Ref`, `BgColorS_Ref`, `FgColorP_Ref`, `BgColorP_Ref`, `Keystroke`, `LayerType_Ref`, `DBTableID` FROM jfn02.`LabelType` WHERE (`DBTableName` = 'MiscLabel');
INSERT INTO jfnwat.`LabelType` (`ID`, `FgColorS_Ref`, `BgColorS_Ref`, `FgColorP_Ref`, `BgColorP_Ref`, `Keystroke`, `LayerType_Ref`, `FrameElement_Ref`) SELECT `ID`, `FgColorS_Ref`, `BgColorS_Ref`, `FgColorP_Ref`, `BgColorP_Ref`, `Keystroke`, `LayerType_Ref`, `DBTableID` FROM jfn02.`LabelType` WHERE (`DBTableName` = 'FrameElement');
INSERT INTO jfnwat.`LabelType` (`ID`, `FgColorS_Ref`, `BgColorS_Ref`, `FgColorP_Ref`, `BgColorP_Ref`, `Keystroke`, `LayerType_Ref`, `ConstructElement_Ref`) SELECT `ID`, `FgColorS_Ref`, `BgColorS_Ref`, `FgColorP_Ref`, `BgColorP_Ref`, `Keystroke`, `LayerType_Ref`, `DBTableID` FROM jfn02.`LabelType` WHERE (`DBTableName` = 'ConstructElement');
INSERT INTO jfnwat.`Label` (`ID`, `CreatedDate`, `CreatedBy`, `LabelType_Ref`, `StartChar`, `EndChar`, `Multi`, `Layer_Ref`, `ModifiedDate`, `InstantiationType_Ref`) SELECT * FROM jfn02.`Label` WHERE (`Layer_Ref` IN (SELECT ID FROM jfnwat.`Layer`));
INSERT INTO jfnwat.`LabelPos`(`ID`,`StartChar`,`EndChar`,`Label_Ref`) SELECT * FROM jfn02.`LabelPos`;
INSERT INTO jfnwat.`NoteLink` (`ID`, `Note_Ref`, `LexUnit_Ref`) SELECT `ID`,`Note_Ref`, `DBTableID` FROM jfn02.`NoteLink` WHERE (`DBTableName` = 'LexUnit') AND (`DBTableID` IN (SELECT ID FROM LexUnit));
INSERT INTO jfnwat.`NoteLink` (`ID`, `Note_Ref`, `Frame_Ref`) SELECT `ID`,`Note_Ref`, `DBTableID` FROM jfn02.`NoteLink` WHERE (`DBTableName` = 'Frame');
INSERT INTO jfnwat.`NoteLink` (`ID`, `Note_Ref`, `FrameElement_Ref`) SELECT `ID`,`Note_Ref`, `DBTableID` FROM jfn02.`NoteLink` WHERE (`DBTableName` = 'FrameElement');
SET foreign_key_checks = 1;
